services:
  db:
    image: mongo:7
    container_name: tft_db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongodata:/data/db
    ports:
      - "27018:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  ingestion:
    build:
      context: ./ingestion
      dockerfile: Dockerfile
    container_name: tft_ingestion
    restart: unless-stopped
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./ingestion:/app

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: tft_api
    restart: unless-stopped
    env_file: .env
    depends_on:
      db:
        condition: service_started
    ports:
      - "8000:8000"
    volumes:
      - ./ml:/app/ml
      - ./api:/app

  mongo-express:
    image: mongo-express:latest
    container_name: tft_mongo_express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: db
    ports:
      - "8081:8081"
    depends_on:
      - db

volumes:
  mongodata: